In [16]:
from tensorflow.keras.preprocessing.text import one_hot


In [17]:
sent=[
    'I love my dog',
    'I love my cat',
    'You love my dog!',
    'Do you think my dog is amazing?',
    'i am good developer'
]
voc_size=10000
onehot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr)

[[2765, 3009, 3352, 152], [2765, 3009, 3352, 6221], [5598, 3009, 3352, 152], [5466, 5598, 1137, 3352, 152, 7303, 2095], [2765, 3863, 6095, 8640]]


In [18]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [19]:
sent_lenght=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_lenght)
print(embedded_docs)

[[   0    0    0    0 2765 3009 3352  152]
 [   0    0    0    0 2765 3009 3352 6221]
 [   0    0    0    0 5598 3009 3352  152]
 [   0 5466 5598 1137 3352  152 7303 2095]
 [   0    0    0    0 2765 3863 6095 8640]]


In [20]:
## feature representation
dim=10
model=Sequential()
model.add(Embedding(voc_size, dim, input_length=sent_lenght))
model.build(input_shape=(None, sent_lenght))  # ensure weights exist so summary shows params
model.compile('adam','mse')

In [21]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [22]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 191ms/step


array([[[-0.02901008,  0.0003302 , -0.02535161, -0.04620204,
         -0.02258695, -0.03478304, -0.02131293,  0.00950955,
         -0.04191192, -0.00133722],
        [-0.02901008,  0.0003302 , -0.02535161, -0.04620204,
         -0.02258695, -0.03478304, -0.02131293,  0.00950955,
         -0.04191192, -0.00133722],
        [-0.02901008,  0.0003302 , -0.02535161, -0.04620204,
         -0.02258695, -0.03478304, -0.02131293,  0.00950955,
         -0.04191192, -0.00133722],
        [-0.02901008,  0.0003302 , -0.02535161, -0.04620204,
         -0.02258695, -0.03478304, -0.02131293,  0.00950955,
         -0.04191192, -0.00133722],
        [ 0.02683381,  0.01296293, -0.01271544,  0.0343479 ,
         -0.0464308 ,  0.01872091,  0.00657585,  0.01441692,
         -0.04519106, -0.03847193],
        [ 0.02850653, -0.03831974,  0.0171881 ,  0.04571693,
          0.04150857, -0.0156019 , -0.00770678,  0.04890788,
         -0.00836722, -0.02915868],
        [-0.04375503,  0.03782633,  0.02118336, -0.0